In [14]:
import pandas as pd
seoul_cctv = pd.read_csv("./data/seoul_cctv.csv", encoding='utf-8')
seoul_cctv.head()
#seoul_cctv.columns
#seoul_cctv.columns[0]
seoul_cctv.rename(columns={seoul_cctv.columns[0] : "구별" }, inplace=True)
seoul_cctv

      구별    소계  2013년도 이전  2014년  2015년  2016년
0    강남구  3238       1292    430    584    932
1    강동구  1010        379     99    155    377
2    강북구   831        369    120    138    204
3    강서구   911        388    258    184     81
4    관악구  2109        846    260    390    613
5    광진구   878        573     78     53    174
6    구로구  1884       1142    173    246    323
7    금천구  1348        674     51    269    354
8    노원구  1566        542     57    451    516
9    도봉구   825        238    159     42    386
10  동대문구  1870       1070     23    198    579
11   동작구  1302        544    341    103    314
12   마포구   980        314    118    169    379
13  서대문구  1254        844     50     68    292
14   서초구  2297       1406    157    336    398
15   성동구  1327        730     91    241    265
16   성북구  1651       1009     78    360    204
17   송파구  1081        529     21     68    463
18   양천구  2482       1843    142     30    467
19  영등포구  1277        495    214    195    373
20   용산구  2096       1368    218    112    398
21   은평구  2108       1138    224    278    468
22   종로구  1619        464    314    211    630
23    중구  1023        413    190     72    348
24   중랑구   916        509    121    177    109

In [31]:
PopulateSeoul = pd.read_excel("./data/populationSeoul.xls", encoding='utf-8', header=2, usecols='B, D, G, J, N')
PopulateSeoul.head()
PopulateSeoul.rename(columns={
    PopulateSeoul.columns[0] : "구별",
    PopulateSeoul.columns[1] : "인구수",
    PopulateSeoul.columns[2] : "한국인",
    PopulateSeoul.columns[3] : "외국인",
    PopulateSeoul.columns[4] : "고령자"
    },inplace=True)
PopulateSeoul

      구별       인구수      한국인     외국인      고령자
0     합계  10197604  9926968  270636  1321458
1    종로구    162820   153589    9231    25425
2     중구    133240   124312    8928    20764
3    용산구    244203   229456   14747    36231
4    성동구    311244   303380    7864    39997
5    광진구    372164   357211   14953    42214
6   동대문구    369496   354079   15417    54173
7    중랑구    414503   409882    4621    56774
8    성북구    461260   449773   11487    64692
9    강북구    330192   326686    3506    54813
10   도봉구    348646   346629    2017    51312
11   노원구    569384   565565    3819    71941
12   은평구    494388   489943    4445    72334
13  서대문구    327163   314982   12181    48161
14   마포구    389649   378566   11083    48765
15   양천구    479978   475949    4029    52975
16   강서구    603772   597248    6524    72548
17   구로구    447874   416487   31387    56833
18   금천구    255082   236353   18729    32970
19  영등포구    402985   368072   34913    52413
20   동작구    412520   400456   12064    56013
21   관악구    525515   507203   18312    68082
22   서초구    450310   445994    4316    51733
23   강남구    570500   565550    4950    63167
24   송파구    667483   660584    6899    72506
25   강동구    453233   449019    4214    54622